### ISSUE TITLE
Disable character echo back

### ISSUE THREAD

**Issue by DRSDavidSoft** [LennartHennigs/ESPTelnet#64]
Hi there, quick question. Can we stop the user input characters from being returned back to the terminal?

The reason I'm asking this is because I'm passing the I/O of the ESPTelnet to a Shell processor that I wrote some time ago (https://github.com/DRSDavidSoft/Ardush) and it already echos the character back when it's necessary.

So it would be useful to turn off the echo at the ESPTelnet.

Also on a side note, can you please remove the ESP8266WebServer.h inclusion if it's not doing anything useful? It's conflicting with the https://github.com/me-no-dev/ESPAsyncWebServer library.

Thank you.

**Update:** I found this useful stackoverflow post: https://stackoverflow.com/a/28571812/1454514

This seems to solve the issue I have when using Microsoft's Telnet:

```cpp
// callback functions for telnet events
void onTelnetConnect(String ip) {
	telnet.print(ansi.cls());
	telnet.print(ansi.home());
	telnet.print(ansi.setFG(ANSI_BRIGHT_GREEN));
	telnet.println("\nWelcome " + telnet.getIP() + " to " + WiFi.hostname() + "!");
	telnet.print(ansi.reset());

	// disable local echo
	telnet.write(0xFF);    // IAC
	telnet.write(0xFB);    // WILL
	telnet.write(0x01);    // ECHO

	newPrompt();
}
```

**Comment by LennartHennigs** [comment]
Ah, I see. Glad that you found it.
The issue is about Telnet (Feature) Negotiation on the other side.

As a reference for others, [I found this article helpful.](https://www.omnisecu.com/tcpip/telnet-negotiation.php?expand_article=1). 

For your information, I looked into the topic a while ago and decided it is not part of this lib—for now, at least.
